<meta name="description" content="Общественная организация по занятиям Айкидо Айкикай в Саратове">
<meta name="keywords" content="айкидо, саратов, айкидо саратов, клубы айкидо, психологическое айкидо,
                                        школы айкидо, школа айкидо, секция айкидо, занятия айкидо, семинары айкидо,
                                        айкидо центры, айкидо России, секция айкидо саратов, клуб айкидо саратов,
                                        что такое айкидо, Станислав Петров, Михаил Сафронов, Кристиан Тисье,
                                        Кристиан Тиссье, Патрик Бенези, Сейширо Эндо, бокен, танто, атеми, укеми
                                        aikido, aikikai, Stanislav Petrov, Mikhail Safronov, Christian Tissier,
                                        Patrick Behezi, aikiken, айкидо для детей, спорт, рукопашный бой, самооборона">



<meta charset="utf-8">
<title>Саратовская Федерация Айкидо Айкикай</title>
<link rel="stylesheet" href="/styles/MyStyle.css">

<script>
    $(
        function () {
            $('#head').load('/includes/head.inc')
        }
    );
</script>
<script>
    $(
        function () {
            $('#menu').load('/includes/menu.inc')
        }
    );
</script>
<script>
    $(
        function () {
            $('#right').load('/includes/right.inc')
        }
    );
</script>
<script>
    $(
        function () {
            $('#creators').load('/includes/creators.inc')
        }
    );
</script>