
            <td height="20" colspan="2" align="right" valign="bottom">
                <span class="for_creators_style">
                    Дизайн:
                    <a href="mailto:idomanskaya@yandex.ru" class="for_creators_style"> Domanskaya I</a><a href="mailto:pushtaeva@yandex.ru" class="for_creators_style">,</a>
                    Изготовление сайта:
                    <a href="mailto:dfhrhfan12@yandex.ru" class="for_creators_style"> Петров А</a><a href="https://vk.com/id60983070" class="for_creators_style">.</a>
                </span>
            </td>